apiVersion: v1
kind: ConfigMap
metadata:
  name: my-config
data:
  app_name: "my-app"
  app_version: "1.0"
---
apiVersion: v1
kind: Secret
metadata:
  name: my-secret
stringData:
  username: admin
  password: password123
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx
  name: config-secrets-pod
spec:
  containers:
  - image: nginx:latest
    name: nginx
    env:
    - name: APP-NAME
      valueFrom:
        configMapKeyRef:
          name: my-config
          key: app_name
    - name: APP-VERSION
      valueFrom:
        configMapKeyRef:
          name: my-config
          key: app_version
    - name: USERNAME
      valueFrom:
        secretKeyRef:
          name: my-secret
          key: username
    - name: PASSWORD
      valueFrom:
        secretKeyRef:
          name: my-secret
          key: password
  dnsPolicy: ClusterFirst
  restartPolicy: Always
