apiVersion: v1
kind: Secret
metadata:
  name: database-credentials
type: Opaque
data:
  username: YWRtaW4=
  password: cGFzc3dvcmQ=

# apiVersion: v1
# kind: Secret
# metadata:
#   name: demo-secret
# type: Opaque
# stringData:
#   username: admin
#   password: password
