apiVersion: v1
kind: Pod
metadata:
  name: configmap-args-example
spec:
  containers:
    - name: my-container
      image: nginx
      command:
        - "/bin/sh"
        - "-c"
        - "echo $(KEY1)"
      env:
        - name: KEY1
          valueFrom:
            configMapKeyRef:
              name: my-config
              key: key1