# overlays/dev/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 2 # Increase replicas for the dev environment
  template:
    spec:
      containers:
        - name: my-app
          image: nginx:1.15 # Use the dev or different version of the image