apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1 # Maximum number of pods that can be created above the desired number of pods
      maxUnavailable: 1 # Maximum number of pods that can be unavailable during the update
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-app-container
          image: nginx:1.26 # Updated image version. nginx:1.26 nginx:1.15
          ports:
          - containerPort: 80
