apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-http-and-db-traffic
spec:
  podSelector:
    matchLabels:
      app: my-app
  ingress:
  - ports:
    - protocol: TCP
      port: 80
  egress:
    - to:
      - ipBlock:
        cidr: 192.168.0.0/16
  policyTypes:
    - Ingress
    - Egress
