apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: cacheclusters.example.com
spec:
  group: example.com
  names:
    kind: CacheCluster
    listKind: CacheClusterList
    plural: cacheclusters
    singular: cachecluster
  scope: Namespaced #Whether namespaced for cluster-scoped.
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec: #Fields the resource will have
              type: object
              properties:
                size:
                  type: integer
                  description: "Size of the cache"
                  example: 3
                engine:
                  type: string
                  description: "Cache engine (e.g., Redis)"
                  example: "redis"
